// PRD §9 — taxonomy of categories (confirmed). Do not change without updating
// the PRD; downstream dashboards group by these exact values.
export const CATEGORIES = [
  "suporte/dúvida",
  "oportunidade/parceria",
  "convite",
  "fã/feedback",
  "networking",
  "cold outreach/venda",
  "financeiro/fornecedor",
  "interno/equipe",
  "pessoal/família",
  "outro",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const SENTIMENTS = ["positivo", "neutro", "negativo"] as const;
export type Sentiment = (typeof SENTIMENTS)[number];

// Generic conversational acts / media formats that are NOT real pautas. Shared by
// the API topic surfaces (private intelligence / content-ideas / group cloud) and
// the build-topics clustering job so noise is filtered consistently. Compared
// against lower(trim(topic)).
export const TOPIC_BLACKLIST: string[] = [
  // saudações / despedidas
  "saudação",
  "saudações",
  "saudacao",
  "saudacoes",
  "cumprimento",
  "cumprimentos",
  "bom dia",
  "boa tarde",
  "boa noite",
  "despedida",
  "despedidas",
  "conversa casual",
  "conversa informal",
  "conversa",
  "bate-papo",
  "papo",
  // agradecimentos
  "agradecimento",
  "agradecimentos",
  "agradecer",
  // confirmações / negações / respostas genéricas
  "confirmação",
  "confirmações",
  "confirmacao",
  "confirmacoes",
  "negação",
  "negações",
  "negacao",
  "negacoes",
  "concordância",
  "concordancia",
  "discordância",
  "discordancia",
  "aceite",
  "recusa",
  "resposta",
  "respostas",
  "resposta genérica",
  "pergunta genérica",
  "elogio",
  "elogios",
  "risada",
  "risadas",
  "mensagem curta",
  "mensagem genérica",
  // formato / mídia (não são pautas)
  "gravação",
  "gravacao",
  "áudio",
  "audio",
  "imagem",
  "foto",
  "vídeo",
  "video",
  "figurinha",
  "sticker",
  "emoji",
  "mídia",
  "midia",
  "mensagem",
  "status",
  "outros",
  "outro",
  "geral",
  "diversos",
];

// Extra noise filtered ONLY from the group theme surfaces (overview cloud +
// cross-group clustering). These are conversational acts / meta-tópicos that swamp
// groups but can be legitimate pautas in the privado, so the privado surfaces keep
// using TOPIC_BLACKLIST alone.
export const GROUP_TOPIC_BLACKLIST: string[] = [
  ...TOPIC_BLACKLIST,
  // comentários / menções / reações genéricas (atos de conversa, não pautas)
  "comentário",
  "comentario",
  "comentários",
  "comentarios",
  "comentário genérico",
  "comentario generico",
  "comentário pessoal",
  "comentario pessoal",
  "comentário positivo",
  "comentario positivo",
  "comentário negativo",
  "comentario negativo",
  "menção",
  "mencao",
  "menções",
  "mencoes",
  "humor",
  "piada",
  "piadas",
  "brincadeira",
  "brincadeiras",
  "motivação",
  "motivacao",
  "motivacional",
  "mensagem motivacional",
  "parabéns",
  "parabens",
  "felicitação",
  "felicitações",
  "felicitacao",
  "felicitacoes",
  "boas-vindas",
  "boas vindas",
  "bem-vindo",
  "bem-vinda",
  "feedback",
  "feedbacks",
  "feedback positivo",
  "feedback negativo",
  "aprovação",
  "aprovacao",
  "comunicação",
  "comunicacao",
  "comunicação interna",
  "comunicacao interna",
  // links / compartilhamentos (formato, não pauta)
  "link",
  "links",
  "link compartilhado",
  "compartilhamento de link",
  "compartilhamento",
  "compartilhamento de conteúdo",
  "compartilhamento de conteudo",
  "comentário casual",
  "comentario casual",
  "reação positiva",
  "reacao positiva",
  "reação",
  "reacao",
  "expressão",
  "expressao",
  "confirmação de ação",
  "confirmacao de acao",
];
